// FC 27 LE Turbo GUI - 3D looks of the real faces: skin, hair colour, hair length, hair type, facial hair, beard colour and
// headwear of each real-face player as the game's 3D render of his head shows them (turbo_output/cache/faces3d
// p_<playerid>.dds). For real faces the game takes hair, beard, skin and eyes from the face scan, so the database codes
// (skintonecode, haircolorcode, hairtypecode, facialhairtypecode ...) do not describe the head; the real-face chooser
// (core/face_filter.h, ui_faces.cpp) filters on these looks instead.
// The data is core/face3d_looks_data.h, generated by scripts/gen_face3d_looks.py from the classification CSVs (merged copy:
// turbogui/data/face3d_looks.csv). Platform independent. Managers have no 3D looks.
#pragma once
#include <cstddef>
#include <cstdint>
#include <string>

namespace turbo::face3d {

// The traits of a look, and the values of each (the order of the generator's word lists: append only)
enum Trait { kSkin, kHairColour, kHairLength, kHairType, kFacialHair, kBeardColour, kHeadwear, kTraitCount };
enum Skin : uint8_t { kSkinVeryLight, kSkinLight, kSkinMedium, kSkinOlive, kSkinBrown, kSkinDark, kSkinCount };
enum HairColour : uint8_t {
    kHairBlack, kHairDarkBrown, kHairBrown, kHairLightBrown, kHairBlonde, kHairRed, kHairGrey, kHairWhite, kHairDyed, kHairNone,
    kHairColourCount
};
enum HairLength : uint8_t { kBald, kBuzz, kShort, kMedium, kLong, kHairLengthCount };
enum HairType : uint8_t {
    kStraight, kWavy, kCurly, kAfro, kBraids, kDreads, kTwists, kTied, kMohawk, kSlicked, kSpiky, kOtherType, kHairTypeCount
};
enum FacialHair : uint8_t { kClean, kStubble, kMoustache, kGoatee, kShortBeard, kFullBeard, kLongBeard, kFacialHairCount };
enum BeardColour : uint8_t {
    kBeardNone, kBeardBlack, kBeardDarkBrown, kBeardBrown, kBeardBlonde, kBeardRed, kBeardGrey, kBeardColourCount
};
enum Headwear : uint8_t { kNoHeadwear, kHeadband, kHairband, kHat, kHeadwearCount };

constexpr int kMaxValues = 12;  // values of the largest trait (hair type)

struct Look {
    int32_t id;              // playerid
    uint8_t v[kTraitCount];  // value of each trait (Skin, HairColour, ... in Trait order)
};

const Look* lookup(int64_t playerid);  // the player's 3D look, nullptr when his head is not classified (yet)
size_t count();                        // looks in the table
const Look* all();                     // sorted by id, count() entries

const char* trait_title(int trait);         // "Skin tone", "Hair colour", "Hair length", "Hair type", "Facial hair", "Beard colour", "Headwear"
int value_count(int trait);                 // values of a trait (6 skin tones .. 12 hair types), 0 for a bad trait
const char* value_name(int trait, int v);   // readable: "Very light", "Dark brown", "Short beard", "Hat / cap"; "?" when out of range
const char* value_word(int trait, int v);   // the CSV word: "very_light", "dark_brown", "short_beard", "hat"; "" when out of range
int parse_value(int trait, const std::string& word);  // index of a CSV word (case and spaces ignored), -1 when unknown
// One CSV row "id,skin,hair_colour,hair_length,hair_type,facial_hair,beard_colour,headwear" (the generator's rules: 8
// columns, id 1 .. 2^31-1, every word in its list); false for a bad row or the header
bool parse_row(const std::string& line, Look* out);
// "light skin, dark brown short wavy hair, short beard (dark brown), no headwear"
std::string describe(const Look& l);

// Tests: use another table (sorted by id, kept alive by the caller) instead of the generated one; nullptr restores it.
// generation() changes on every call, so lists holding look pointers know to rebuild.
void use_table(const Look* t, size_t n);
uint64_t generation();

}  // namespace turbo::face3d
