// FC 27 LE Turbo GUI - hair catalog: the look of every FC 27 hair style (hairtypecode) by length, type and accessory,
// for the player editor's hair gallery filters (ui_images.cpp) and the real-face chooser's Hair facet (face_filter.cpp).
// Platform independent. The data is core/hair_styles_data.h, generated by scripts/gen_hair_styles.py from the
// classification of the game's preview pictures (craniumhair hair_<id>_0); unclassified ids carry the face_looks.h
// length, type Other and no accessory (classified == false).
#pragma once
#include <cstddef>
#include <cstdint>
#include <string>

namespace turbo::hair {

// kUnknownLength: the game's preview shows a placeholder bucket hat, so the real style is not visible
enum Length : uint8_t { kBald, kBuzz, kShort, kMedium, kLong, kUnknownLength, kLengthCount };
enum Type : uint8_t { kStraight, kWavy, kCurly, kAfro, kBraids, kDreads, kTwists, kTied, kMohawk, kSlicked, kSpiky, kOther, kTypeCount };
enum Accessory : uint8_t { kNoAccessory, kHeadband, kHairband, kHairTie, kHat, kAccessoryCount };  // kHat: cap / beanie / durag ...

struct Style {
    int16_t id;
    uint8_t length, type, accessory, classified;
};

const Style* find(int64_t id);  // the catalog entry, nullptr if the id is not listed
Style lookup(int64_t id);       // never fails: an unlisted id is {id, Short, Other, None, unclassified}
size_t count();
const Style* all();             // sorted by id, count() entries

const char* length_name(int length);        // "Bald", "Buzz cut", "Short", "Medium", "Long", "Unknown (no preview)"
const char* type_name(int type);            // "Straight" .. "Ponytail / bun / top knot" .. "Other"
const char* accessory_name(int accessory);  // "None", "Headband", "Alice band / hairband", "Hair tie / clips", "Hat / cap / durag"
std::string describe(const Style& s);       // "Long, curly, headband" (no accessory and type Other are left out)

}  // namespace turbo::hair
