// Native tests: the hair catalog (core/hair_catalog.h, data generated by scripts/gen_hair_styles.py into
// core/hair_styles_data.h). Included by test_main.cpp, run from main with the other core tests.
#pragma once
#include "core/face_looks.h"
#include "core/hair_catalog.h"

// The real-face chooser's Hair bucket a classified catalog style must land in (face_filter.cpp hair_bucket)
static int64_t hair_catalog_bucket(const turbo::hair::Style& s) {
    using namespace turbo::hair;
    if (s.length == kBald || s.length == kBuzz) return 1;
    if (s.type == kBraids || s.type == kDreads || s.type == kTwists || s.type == kTied) return 5;
    return s.length == kShort ? 2 : s.length == kMedium ? 3 : 4;
}

static void test_hair_catalog() {
    using namespace turbo;
    run_case("Hair catalog: generated data is sorted, in range and covers every face_looks.h hair style", [] {
        const hair::Style* a = hair::all();
        const size_t n = hair::count();
        CHECK(n >= std::size(faces::looks::kHair), "at least the 1463 face_looks.h styles");
        bool sorted = true, ranged = true;
        for (size_t i = 0; i < n; ++i) {
            if (i && a[i - 1].id >= a[i].id) sorted = false;
            if (a[i].id < 0 || a[i].length >= hair::kLengthCount || a[i].type >= hair::kTypeCount ||
                a[i].accessory >= hair::kAccessoryCount || a[i].classified > 1)
                ranged = false;
        }
        CHECK(sorted, "ids strictly ascending (binary search)");
        CHECK(ranged, "every length / type / accessory inside its word list");
        size_t missing = 0, bad_fallback = 0;
        for (const auto& e : faces::looks::kHair) {
            const hair::Style* s = hair::find(e.id);
            if (!s) { ++missing; continue; }
            if (s->classified) continue;
            // unclassified: the face_looks.h length, type Other, no accessory
            const int want = e.look == faces::looks::B ? hair::kBuzz : e.look == faces::looks::S ? hair::kShort
                             : e.look == faces::looks::L ? hair::kLong : hair::kMedium;
            if (s->length != want || s->type != hair::kOther || s->accessory != hair::kNoAccessory) ++bad_fallback;
        }
        CHECK(missing == 0, "every face_looks.h hair id is in the catalog");
        CHECK(bad_fallback == 0, "unclassified ids fall back to the face_looks.h length, type Other, no accessory");
    });
    run_case("Hair catalog: lookup, unknown ids, names and descriptions", [] {
        CHECK(hair::find(0) && hair::find(0)->id == 0, "id 0 listed");
        CHECK(hair::find(50) == nullptr && hair::find(-1) == nullptr && hair::find(99999) == nullptr, "unlisted ids -> nullptr");
        hair::Style u = hair::lookup(99999);
        CHECK(u.id == int16_t(99999 & 0xffff) || u.id != 0, "lookup of an unlisted id never fails");
        u = hair::lookup(50);
        CHECK(u.id == 50 && u.length == hair::kShort && u.type == hair::kOther && u.accessory == hair::kNoAccessory && !u.classified,
              "unlisted id 50 -> Short, Other, no accessory, unclassified");
        CHECK(std::string(hair::length_name(hair::kBuzz)) == "Buzz cut" && std::string(hair::type_name(hair::kAfro)) == "Afro / coily" &&
                  std::string(hair::type_name(hair::kTied)) == "Ponytail / bun / top knot" &&
                  std::string(hair::accessory_name(hair::kHairband)) == "Alice band / hairband" &&
                  std::string(hair::accessory_name(hair::kHat)) == "Hat / cap / durag" &&
                  std::string(hair::length_name(hair::kUnknownLength)) == "Unknown (no preview)" &&
                  std::string(hair::length_name(99)) == "?" && std::string(hair::type_name(-1)) == "?",
              "names");
        hair::Style s{7, hair::kLong, hair::kCurly, hair::kHeadband, 1};
        CHECK(hair::describe(s) == "Long, curly, headband", "describe: Long, curly, headband");
        s = hair::Style{7, hair::kShort, hair::kOther, hair::kNoAccessory, 0};
        CHECK(hair::describe(s) == "Short", "describe leaves out type Other and no accessory");
        s = hair::Style{7, hair::kMedium, hair::kBraids, hair::kHairTie, 1};
        CHECK(hair::describe(s) == "Medium, braids / cornrows, hair tie / clips", "describe: braids with a hair tie");
    });
    run_case("Hair catalog: the real-face chooser's Hair facet follows the catalog for classified styles", [] {
        size_t wrong = 0, classified = 0;
        for (size_t i = 0; i < hair::count(); ++i) {
            const hair::Style& s = hair::all()[i];
            if (!s.classified || s.length == hair::kUnknownLength) continue;
            ++classified;
            if (faces::facet_key(faces::kHair, s.id) != hair_catalog_bucket(s)) ++wrong;
        }
        CHECK(wrong == 0, "every classified style in its length / tied bucket (" + std::to_string(classified) + " classified)");
    });
}
