// Native tests: the 3D looks of the real faces (core/face3d_looks.h, data generated by scripts/gen_face3d_looks.py into
// core/face3d_looks_data.h from turbogui/data/face3d_looks.csv) and the real-face chooser's 3D facets (core/face_filter.h).
// Included by test_main.cpp, run from main with the other core tests.
#pragma once
#include "core/face3d_looks.h"
#include "core/face_filter.h"

static void test_face3d_looks() {
    using namespace turbo;
    run_case("3D looks: generated header = data/face3d_looks.csv (gen output parses, sorted, in range)", [] {
        const face3d::Look* a = face3d::all();
        const size_t n = face3d::count();
        bool sorted = true, ranged = true;
        for (size_t i = 0; i < n; ++i) {
            if (i && a[i - 1].id >= a[i].id) sorted = false;
            for (int t = 0; t < face3d::kTraitCount; ++t)
                if (a[i].v[t] >= face3d::value_count(t)) ranged = false;
        }
        CHECK(sorted && ranged && n > 0, fmt("%zu looks, ids strictly ascending, every value inside its word list", n));
        // the merged CSV kept in the repo: every row parses with the generator's rules and is the compiled look
        const fs::path csv = fs::path(g_lua).parent_path().parent_path().parent_path() / "data" / "face3d_looks.csv";
        std::ifstream in(csv);
        CHECK(in.good(), "data/face3d_looks.csv: " + csv.string());
        std::string line;
        size_t rows = 0, bad = 0, differ = 0;
        std::getline(in, line);
        CHECK(line.rfind("id,skin,hair_colour,hair_length,hair_type,facial_hair,beard_colour,headwear", 0) == 0, "CSV header");
        while (std::getline(in, line)) {
            if (line.empty()) continue;
            face3d::Look l{};
            if (!face3d::parse_row(line, &l)) {
                ++bad;
                continue;
            }
            ++rows;
            const face3d::Look* c = face3d::lookup(l.id);
            if (!c || std::memcmp(c->v, l.v, sizeof(l.v)) != 0) ++differ;
        }
        CHECK(bad == 0 && rows == n && differ == 0, fmt("%zu CSV rows (%zu bad, %zu differ from the header) for %zu looks", rows, bad, differ, n));
    });

    run_case("3D looks: CSV rows, names, lookup, describe", [] {
        face3d::Look l{};
        CHECK(face3d::parse_row("230666,light,dark_brown,short,wavy,short_beard,dark_brown,none\r", &l) && l.id == 230666 &&
                  l.v[face3d::kSkin] == face3d::kSkinLight && l.v[face3d::kHairColour] == face3d::kHairDarkBrown &&
                  l.v[face3d::kHairLength] == face3d::kShort && l.v[face3d::kHairType] == face3d::kWavy &&
                  l.v[face3d::kFacialHair] == face3d::kShortBeard && l.v[face3d::kBeardColour] == face3d::kBeardDarkBrown &&
                  l.v[face3d::kHeadwear] == face3d::kNoHeadwear,
              "a good row (CRLF)");
        CHECK(face3d::parse_row(" 7 , Very_Light ,NONE,bald,other,clean,none,hat", &l) && l.id == 7 && l.v[face3d::kSkin] == face3d::kSkinVeryLight &&
                  l.v[face3d::kHeadwear] == face3d::kHat,
              "spaces and case ignored");
        CHECK(!face3d::parse_row("id,skin,hair_colour,hair_length,hair_type,facial_hair,beard_colour,headwear", nullptr) &&
                  !face3d::parse_row("239807,light,light_brown,short,straight,stubble,light_brown,none", nullptr) &&  // no light_brown beard
                  !face3d::parse_row("1,light,black,short,wavy,clean,none", nullptr) &&                              // 7 columns
                  !face3d::parse_row("1,light,black,short,wavy,clean,none,none,x", nullptr) &&                       // 9 columns
                  !face3d::parse_row("0,light,black,short,wavy,clean,none,none", nullptr) &&                         // id 0
                  !face3d::parse_row("-5,light,black,short,wavy,clean,none,none", nullptr) &&
                  !face3d::parse_row("99999999999,light,black,short,wavy,clean,none,none", nullptr) &&
                  !face3d::parse_row("12a,light,black,short,wavy,clean,none,none", nullptr) &&
                  !face3d::parse_row("", nullptr),
              "bad rows are refused (the generator skips them)");
        CHECK(std::string(face3d::value_name(face3d::kSkin, face3d::kSkinVeryLight)) == "Very light" &&
                  std::string(face3d::value_name(face3d::kHairColour, face3d::kHairDarkBrown)) == "Dark brown" &&
                  std::string(face3d::value_name(face3d::kFacialHair, face3d::kShortBeard)) == "Short beard" &&
                  std::string(face3d::value_name(face3d::kHeadwear, face3d::kHat)) == "Hat / cap" &&
                  std::string(face3d::value_name(face3d::kSkin, 6)) == "?" && std::string(face3d::trait_title(face3d::kHeadwear)) == "Headwear" &&
                  face3d::value_count(face3d::kHairType) == face3d::kMaxValues && face3d::value_count(face3d::kSkin) == 6 &&
                  face3d::parse_value(face3d::kHairColour, "dyed") == face3d::kHairDyed && face3d::parse_value(face3d::kHairColour, "pink") == -1,
              "readable names and words");
        const face3d::Look sample = {230666, {face3d::kSkinLight, face3d::kHairDarkBrown, face3d::kShort, face3d::kWavy, face3d::kShortBeard,
                                              face3d::kBeardDarkBrown, face3d::kNoHeadwear}};
        CHECK(face3d::describe(sample) == "light skin, dark brown short wavy hair, short beard (dark brown), no headwear", face3d::describe(sample));
        const face3d::Look bald = {8, {face3d::kSkinDark, face3d::kHairNone, face3d::kBald, face3d::kOtherType, face3d::kClean, face3d::kBeardNone,
                                       face3d::kHat}};
        CHECK(face3d::describe(bald) == "dark skin, bald, clean-shaven, hat / cap", face3d::describe(bald));
        // lookup: a test table instead of the generated one
        static const face3d::Look table[] = {{10, {0, 0, 0, 0, 0, 0, 0}}, {20, {1, 1, 1, 1, 1, 1, 1}}, {30, {2, 2, 2, 2, 2, 2, 2}}};
        const size_t generated = face3d::count();
        const uint64_t g0 = face3d::generation();
        face3d::use_table(table, 3);
        CHECK(face3d::count() == 3 && face3d::lookup(20) == &table[1] && face3d::lookup(10) == &table[0] && face3d::lookup(30) == &table[2] &&
                  !face3d::lookup(15) && !face3d::lookup(31) && !face3d::lookup(0) && !face3d::lookup(-1) && face3d::generation() != g0,
              "lookup: binary search, nullptr for an unclassified id");
        face3d::use_table(nullptr, 0);
        CHECK(face3d::count() == generated && face3d::all() != table, "generated table restored");
    });

    run_case("Real-face chooser with 3D looks: 3D facets, 'not classified yet', every value offered, database facets last", [] {
        using namespace faces;
        static const face3d::Look looks[] = {
            {1, {face3d::kSkinLight, face3d::kHairDarkBrown, face3d::kShort, face3d::kWavy, face3d::kShortBeard, face3d::kBeardDarkBrown, face3d::kNoHeadwear}},
            {2, {face3d::kSkinDark, face3d::kHairBlack, face3d::kShort, face3d::kAfro, face3d::kClean, face3d::kBeardNone, face3d::kNoHeadwear}},
            {3, {face3d::kSkinLight, face3d::kHairBlonde, face3d::kLong, face3d::kTied, face3d::kClean, face3d::kBeardNone, face3d::kHeadband}},
        };
        auto mk = [](int64_t id, int64_t gender, int64_t eyes, const face3d::Look* look) {
            Face f;
            f.id = id;
            f.headassetid = id;
            f.real = true;
            f.name = "P" + std::to_string(id);
            f.raw[kGender] = gender;
            f.raw[kEyes] = eyes;
            f.raw[kSkin] = 20;        // the database says Caucasian 2 for all: the 3D facets ignore it
            f.raw[kHairColour] = 3;   // Dark Brown
            f.raw[kEthnicity] = 34;
            set_look(f, look);
            return f;
        };
        std::vector<Face> heads = {mk(1, 0, 3, &looks[0]), mk(2, 0, 3, &looks[1]), mk(3, 1, 5, &looks[2]), mk(4, 0, 3, nullptr), mk(5, 1, 3, nullptr)};
        std::vector<size_t> pool = {0, 1, 2, 3, 4};
        CHECK(count_looks(heads) == 3 && heads[3].raw[kSkin3d] == kUnclassified && heads[0].raw[kHairType3d] == face3d::kWavy &&
                  heads[0].look == &looks[0] && !heads[4].look,
              "set_look: the look's values, kUnclassified without a look");
        // facets: Gender, the 7 3D facets, then Eyes / Ethnicity "(database)"; managers keep the database facets
        const Facet* o = facet_order(true);
        CHECK(facet_order_size(true) == 10 && o[0] == kGender && o[1] == kSkin3d && o[7] == kHeadwear3d && o[8] == kEyes && o[9] == kEthnicity,
              "3D facet order");
        CHECK(std::string(facet_title(kEyes, true)) == "Eyes (database)" && std::string(facet_title(kEthnicity, true)) == "Ethnicity (database)" &&
                  std::string(facet_title(kEyes, false)) == "Eyes" && std::string(facet_title(kSkin3d, true)) == "Skin tone" &&
                  std::string(facet_title(kHeadwear3d)) == "Headwear" && std::string(facet_title(kHairLength3d)) == "Hair length",
              "titles");
        CHECK(facet_order_size(false) == kDbFacetCount && !facet_shown(kSkin3d, false) && facet_shown(kHair, false) && !facet_shown(kHair, true) &&
                  !facet_shown(kHairColour, true) && facet_shown(kEyes, true) && facet_3d(kHeadwear3d) && !facet_3d(kGender) &&
                  std::string(facet_field(kSkin3d)).empty(),
              "database facets without 3D looks (managers)");
        CHECK(key_label(kHairColour3d, face3d::kHairDarkBrown) == "Dark brown" && key_label(kHeadwear3d, face3d::kHat) == "Hat / cap" &&
                  key_label(kFacialHair3d, kUnclassified) == "not classified yet" && trait_label(kFacialHair3d, face3d::kShortBeard) == "Short beard",
              "3D value labels");
        // a head with a look matches only its own values; a head without one never matches a 3D value filter
        Filter flt;
        flt.sel[kHairLength3d] = face3d::kShort;
        CHECK(matches(heads[0], flt) && matches(heads[1], flt) && !matches(heads[2], flt) && !matches(heads[3], flt) && !matches(heads[4], flt),
              "hair length short: 1 and 2 only");
        flt.sel[kHairType3d] = face3d::kWavy;
        CHECK(matches(heads[0], flt) && !matches(heads[1], flt), "short + wavy: 1");
        flt.clear();
        for (int t = 0; t < face3d::kTraitCount; ++t)
            for (int v = 0; v < face3d::value_count(t); ++v) {
                flt.sel[kSkin3d + t] = v;
                CHECK(!matches(heads[3], flt) && !matches(heads[4], flt), fmt("unclassified heads never match %s = %d", face3d::trait_title(t), v));
                flt.sel[kSkin3d + t] = kAny;
            }
        flt.sel[kSkin3d] = kUnclassified;
        CHECK(!matches(heads[0], flt) && matches(heads[3], flt) && matches(heads[4], flt), "'not classified yet': only the heads without a look");
        flt.clear();
        flt.sel[kSkin] = 20;  // a database facet the chooser hides with 3D looks
        drop_hidden(flt, true);
        CHECK(flt.sel[kSkin] == kAny && !flt.active(), "hidden facets do not filter");
        // counts: every value of the trait (0 for the values no head has), then "not classified yet"
        flt.clear();
        std::vector<Count> skins = facet_counts(heads, pool, flt, kSkin3d);
        CHECK(skins.size() == face3d::kSkinCount + 1 && skins[face3d::kSkinLight].n == 2 && skins[face3d::kSkinLight].sample == 0 &&
                  skins[face3d::kSkinDark].n == 1 && skins[face3d::kSkinOlive].n == 0 && skins[face3d::kSkinOlive].sample == kNoSample &&
                  skins.back().key == kUnclassified && skins.back().n == 2,
              fmt("skin counts (%zu values)", skins.size()));
        std::vector<Count> types = facet_counts(heads, pool, flt, kHairType3d);
        CHECK(types.size() == size_t(face3d::kMaxValues) + 1, "all 12 hair types offered (no kMaxBuckets cap)");
        flt.sel[kGender] = 1;  // female: 3 (looked) and 5 (not yet)
        std::vector<Count> heads_wear = facet_counts(heads, pool, flt, kHeadwear3d);
        CHECK(heads_wear.size() == face3d::kHeadwearCount + 1 && heads_wear[face3d::kHeadband].n == 1 && heads_wear[face3d::kNoHeadwear].n == 0 &&
                  heads_wear.back().key == kUnclassified && heads_wear.back().n == 1,
              "counts under the other filters");
        std::vector<Count> looked_only = facet_counts(heads, {0, 1, 2}, Filter(), kHeadwear3d);
        CHECK(looked_only.size() == face3d::kHeadwearCount && looked_only.back().key == face3d::kHat,
              "no 'not classified yet' value when only looked heads are shown");
        // tooltip
        const std::string t1 = head_traits(heads[0], true), t4 = head_traits(heads[3], true), tdb = head_traits(heads[0], false);
        CHECK(t1.find("\n3D look: light skin, dark brown short wavy hair, short beard (dark brown), no headwear") == 0 &&
                  t1.find("\nGender: Male") != std::string::npos && t1.find("\nEyes (database): Brown") != std::string::npos &&
                  t1.find("Ethnicity (database)") != std::string::npos && t1.find("Caucasian 2") == std::string::npos,
              t1);
        CHECK(t4.find("\n3D look: not classified yet") == 0, t4);
        CHECK(tdb.find("3D look") == std::string::npos && tdb.find("\nSkin tone: Caucasian 2") != std::string::npos, tdb);
        CHECK(kOnly3dDefaultMin == 200, "'Only heads with a 3D look' starts on from 200 looks");
        // managers (no looks, never set_look): 3D facets have no value, database filters as before
        Face m;
        m.manager = true;
        m.raw[kSkin] = 30;
        Filter mf;
        mf.sel[kSkin] = 30;
        CHECK(matches(m, mf) && m.raw[kSkin3d] == kNoValue && head_traits(m, false).find("Skin tone: Caucasian 3") != std::string::npos,
              "manager heads keep the database facets");
    });
}
