#!/usr/bin/env python3
"""FC 27 LE Turbo GUI - generate the 3D looks of the real faces (core/face3d_looks.h).

Merges the classification CSVs of the game's 3D head renders (face3d_class_*.csv, header
`id,skin,hair_colour,hair_length,hair_type,facial_hair,beard_colour,headwear`, id = playerid, values from the word lists
below) into
  turbogui/data/face3d_looks.csv           the merged copy kept in the repo (sorted by id; regenerate from it with --repo)
  turbogui/src/core/face3d_looks_data.h    the table compiled into Turbo ({playerid, {skin, hair_colour, ...}} as indexes)
Bad rows (wrong column count, bad id, unknown word) are skipped and counted; when an id is classified twice the last
row wins (files in natural order: face3d_class_2 before face3d_class_10).

usage: gen_face3d_looks.py [folder | csv ...]   (default folder: $FACE3D_CSV_DIR or the session scratchpad)
       gen_face3d_looks.py --repo               (regenerate the header from turbogui/data/face3d_looks.csv only)
"""
import csv, glob, os, re, sys

# Word lists: the order is the index stored in the header (core/face3d_looks.h enums). Append only.
TRAITS = [
    ("skin", ["very_light", "light", "medium", "olive", "brown", "dark"]),
    ("hair_colour", ["black", "dark_brown", "brown", "light_brown", "blonde", "red", "grey", "white", "dyed", "none"]),
    ("hair_length", ["bald", "buzz", "short", "medium", "long"]),
    ("hair_type", ["straight", "wavy", "curly", "afro", "braids", "dreads", "twists", "tied", "mohawk", "slicked", "spiky", "other"]),
    ("facial_hair", ["clean", "stubble", "moustache", "goatee", "short_beard", "full_beard", "long_beard"]),
    ("beard_colour", ["none", "black", "dark_brown", "brown", "blonde", "red", "grey"]),
    ("headwear", ["none", "headband", "hairband", "hat"]),
]
HEADER = ["id"] + [t for t, _ in TRAITS]
DEFAULT_DIR = os.environ.get(
    "FACE3D_CSV_DIR",
    r"C:\Users\cmode\AppData\Local\Temp\claude\C--FC-27-Live-Editor\08cdb9a5-d1f6-4189-98c5-9b3387fb741d\scratchpad")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
REPO_CSV = os.path.join(ROOT, "data", "face3d_looks.csv")
HEADER_H = os.path.join(ROOT, "src", "core", "face3d_looks_data.h")


def natural(path):
    return [int(p) if p.isdigit() else p for p in re.split(r"(\d+)", os.path.basename(path).lower())]


def parse_row(row):
    """A CSV row -> (id, (index, ...)) or None when the row is bad."""
    row = [c.strip().lower() for c in row]
    if len(row) != len(HEADER):
        return None
    try:
        pid = int(row[0])
    except ValueError:
        return None
    if pid <= 0 or pid > 0x7FFFFFFF:
        return None
    vals = []
    for (name, words), w in zip(TRAITS, row[1:]):
        if w not in words:
            return None
        vals.append(words.index(w))
    return pid, tuple(vals)


def read_csvs(paths):
    looks, bad, dup = {}, 0, 0
    for p in paths:
        with open(p, encoding="utf-8-sig", newline="") as fh:
            for n, row in enumerate(csv.reader(fh)):
                if not row or not "".join(row).strip():
                    continue
                if n == 0 and row[0].strip().lower() == "id":
                    continue
                r = parse_row(row)
                if r is None:
                    bad += 1
                    continue
                if r[0] in looks:
                    dup += 1
                looks[r[0]] = r[1]
    return looks, bad, dup


def write_repo_csv(looks):
    os.makedirs(os.path.dirname(REPO_CSV), exist_ok=True)
    with open(REPO_CSV, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(",".join(HEADER) + "\n")
        for pid in sorted(looks):
            fh.write(",".join([str(pid)] + [TRAITS[i][1][v] for i, v in enumerate(looks[pid])]) + "\n")


def write_header(looks):
    out = ["// FC 27 LE Turbo GUI - 3D looks of the real faces (core/face3d_looks.h). GENERATED by scripts/gen_face3d_looks.py",
           "// from data/face3d_looks.csv: do not edit. %d heads classified from the game's 3D renders." % len(looks),
           "// {playerid, {skin, hair_colour, hair_length, hair_type, facial_hair, beard_colour, headwear}}: indexes into the",
           "// word lists of the script (face3d::Skin, HairColour, HairLength, HairType, FacialHair, BeardColour, Headwear).",
           "#pragma once", "", "namespace turbo::face3d::data {", ""]
    if not looks:
        out += ["constexpr Look kLooks[] = {{0, {0, 0, 0, 0, 0, 0, 0}}};  // no data: kCount 0", "constexpr size_t kCount = 0;"]
    else:
        out.append("constexpr Look kLooks[] = {")
        line = "   "
        for pid in sorted(looks):
            cell = " {%d, {%s}}," % (pid, ",".join(str(v) for v in looks[pid]))
            if len(line) + len(cell) > 118:
                out.append(line)
                line = "   "
            line += cell
        out += [line, "};", "constexpr size_t kCount = sizeof(kLooks) / sizeof(kLooks[0]);"]
    out += ["", "}  // namespace turbo::face3d::data", ""]
    with open(HEADER_H, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))


def main(argv):
    args = argv[1:]
    if args == ["--repo"]:
        paths = [REPO_CSV]
    else:
        paths = []
        for a in args or [DEFAULT_DIR]:
            if os.path.isdir(a):
                paths += sorted(glob.glob(os.path.join(a, "face3d_class_*.csv")), key=natural)
            elif os.path.isfile(a):
                paths.append(a)
            else:
                print("not found: %s" % a, file=sys.stderr)
                return 2
    if not paths:
        print("no face3d_class_*.csv found", file=sys.stderr)
        return 2
    looks, bad, dup = read_csvs(paths)
    write_repo_csv(looks)
    write_header(looks)
    print("face3d looks: %d heads from %d CSV file(s), %d bad rows skipped, %d duplicates (last wins)"
          % (len(looks), len(paths), bad, dup))
    print("  %s\n  %s" % (REPO_CSV, HEADER_H))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
