#!/usr/bin/env python3
"""FC 27 LE Turbo GUI - generate src/core/hair_styles_data.h (the hair catalog, core/hair_catalog.h).

Merges the hair classification CSVs (header `id,length,type,accessory`, values from the word lists below) into one
sorted table. Ids that no CSV classifies fall back to the length of core/face_looks.h kHair, type other, accessory none.
Bad rows (unknown words, bad ids, wrong column count) are skipped and counted.

usage: gen_hair_styles.py [csv ...]   (default: hair_class_*.csv in $HAIR_CSV_DIR or the current directory)
"""
import csv, glob, os, re, sys

LENGTHS = ["bald", "buzz", "short", "medium", "long", "unknown"]  # unknown: the preview shows a placeholder hat
TYPES = ["straight", "wavy", "curly", "afro", "braids", "dreads", "twists", "tied", "mohawk", "slicked", "spiky", "other"]
ACCESSORIES = ["none", "headband", "hairband", "tie", "hat"]
# face_looks.h kHair looks: B bald & buzz, S short, M medium, L long, T tied/braids/dreads (length unknown -> medium)
FALLBACK = {"B": "buzz", "S": "short", "M": "medium", "L": "long", "T": "medium"}

HERE = os.path.dirname(os.path.abspath(__file__))
CORE = os.path.join(HERE, "..", "src", "core")


def fallback_lengths(path):
    text = open(path, encoding="utf-8").read()
    body = text[text.index("kHair[]"):]
    body = body[:body.index("};")]
    return {int(i): FALLBACK[l] for i, l in re.findall(r"\{(\d+),([BSMLT])\}", body)}


def read_csvs(paths):
    styles, bad = {}, 0
    for p in paths:
        with open(p, encoding="utf-8-sig", newline="") as fh:
            for n, row in enumerate(csv.reader(fh)):
                row = [c.strip().lower() for c in row]
                if not row or (n == 0 and row[0] == "id"):
                    continue
                try:
                    if len(row) != 4:
                        raise ValueError
                    i = int(row[0])
                    if i < 0 or i > 32767 or row[1] not in LENGTHS or row[2] not in TYPES or row[3] not in ACCESSORIES:
                        raise ValueError
                except ValueError:
                    bad += 1
                    continue
                styles[i] = (row[1], row[2], row[3])
    return styles, bad


def main(argv):
    paths = argv[1:] or sorted(glob.glob(os.path.join(os.environ.get("HAIR_CSV_DIR", "."), "hair_class_*.csv")))
    paths = [p for p in paths if os.path.isfile(p)]
    fb = fallback_lengths(os.path.join(CORE, "face_looks.h"))
    styles, bad = read_csvs(paths)
    rows, from_csv = [], 0
    for i in sorted(set(fb) | set(styles)):
        if i in styles:
            l, t, a = styles[i]
            rows.append((i, LENGTHS.index(l), TYPES.index(t), ACCESSORIES.index(a), 1))
            from_csv += 1
        else:
            rows.append((i, LENGTHS.index(fb[i]), TYPES.index("other"), 0, 0))
    out = ["// FC 27 LE Turbo GUI - hair catalog data (core/hair_catalog.h). GENERATED by scripts/gen_hair_styles.py: do not edit.",
           "// %d styles: %d classified from the preview pictures, %d fall back to the face_looks.h length." % (len(rows), from_csv, len(rows) - from_csv),
           "// {id, length, type, accessory, classified}; length/type/accessory are hair::Length/Type/Accessory.",
           "#pragma once", "", "namespace turbo::hair::data {", "", "constexpr Style kStyles[] = {"]
    line = "   "
    for r in rows:
        cell = " {%d,%d,%d,%d,%d}," % r
        if len(line) + len(cell) > 118:
            out.append(line)
            line = "   "
        line += cell
    out += [line, "};", "", "}  // namespace turbo::hair::data", ""]
    with open(os.path.join(CORE, "hair_styles_data.h"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))
    print("hair_styles_data.h: %d styles, %d from %d CSV file(s), %d fallback, %d bad rows skipped"
          % (len(rows), from_csv, len(paths), len(rows) - from_csv, bad))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
