package.path = (debug.getinfo(1, "S").source:sub(2):match("(.*/)") or "./") .. "?.lua;" .. package.path
local H = require 'h'
local W = require 'world'

print("t02 automatic features, player edits")

local sim = H.setup({ in_cm = true })
W.build(sim, {})

H.case("FC 27 bundled script bug: old event constant names are nil", function()
    require 'imports/career_mode/enums'
    H.eq(ENUM_CM_EVENT_MSG_DAY_PASSED, nil, "old name")
    H.eq(ENUM_FCEGameModesCM_EVENT_MSG_DAY_PASSED, 15, "new name")
    local events = require 'imports/turbo/core/events'
    H.eq(events.resolve("DAY_PASSED"), 15, "turbo resolves")
    H.eq(events.resolve("NOT_AN_EVENT"), nil, "unknown")
end)

H.case("boot with nothing enabled registers no handler (game launch does nothing)", function()
    local enabled = H.turbo().boot({ at_launch = true })
    H.eq(#enabled, 0, "none enabled")
    H.eq(#(sim.handlers["post__CareerModeEvent"] or {}), 0, "no handler")
    local n = 0
    for _ in pairs(TURBO_STATE.listeners) do n = n + 1 end
    H.eq(n, 0, "no automatic listeners")
    sim:fire("post__CareerModeEvent", 0, 15, 0)   -- DAY_PASSED
    H.eq(sim:count_calls("SetPlayerForm"), 0, "nothing applied")
end)

H.case("form_morale auto: applies at boot and on DAY_PASSED, ignores other events", function()
    H.write_config({ auto = { form_morale = { enabled = true, form = 90, morale = 80, fitness = 0 } } })
    local enabled = H.turbo().boot()
    H.eq(enabled[1], "form_morale", "enabled")
    H.eq(#sim.handlers["post__CareerModeEvent"], 1, "one handler")
    H.eq(sim:count_calls("SetPlayerForm"), 26, "applied at boot")
    sim:fire("post__CareerModeEvent", 0, 15, 0)   -- DAY_PASSED
    H.eq(sim:count_calls("SetPlayerForm"), 52, "applied on day passed")
    H.eq(sim:count_calls("SetPlayerMorale"), 52, "morale too")
    H.eq(sim:count_calls("SetPlayerFitness"), 0, "fitness 0 = untouched")
    sim:fire("post__CareerModeEvent", 0, 7, 0)    -- USER_MATCH_COMPLETED: not configured
    H.eq(sim:count_calls("SetPlayerForm"), 52, "other event ignored")
    H.eq(sim.calls.SetPlayerForm[1][2], 90, "form value")
    H.eq(sim.calls.SetPlayerMorale[1][2], 80, "morale value")
end)

H.case("re-running boot does not add a second handler", function()
    H.turbo().boot()
    dofile(H.LE .. "/lua/autorun/turbo_boot.lua")
    H.script("turbo_enable_auto")
    H.eq(#sim.handlers["post__CareerModeEvent"], 1, "still one handler")
end)

H.case("disabling form_morale stops it on the next event", function()
    H.write_config({ auto = { form_morale = { enabled = false } } })
    H.turbo().boot()
    local before = sim:count_calls("SetPlayerForm")
    sim:fire("post__CareerModeEvent", 0, 15, 0)
    H.eq(sim:count_calls("SetPlayerForm"), before, "no more calls")
end)

H.case("form_morale action validates ranges", function()
    H.write_config({ auto = { form_morale = { form = 101 } } })
    local ok, msg = H.turbo().run("form_morale")
    H.eq(ok, false); H.has(msg, "form must be 0 (leave alone) or 0..100")
    H.write_config({ auto = { form_morale = { form = 100, morale = 100, fitness = 96 } } })
    ok, msg = H.turbo().run("form_morale")
    H.eq(ok, false); H.has(msg, "fitness must be 0 (leave alone) or 5..95")
    H.write_config({ auto = { form_morale = { form = 100, morale = 0, fitness = 95 } } })
    local before = sim:count_calls("SetPlayerFitness")
    ok, msg = H.script("turbo_form_morale_apply")
    ok, msg = H.turbo().run("form_morale")
    H.eq(ok, true, msg)
    H.eq(sim:count_calls("SetPlayerFitness") - before, 52, "fitness applied twice x26")
end)

H.case("pap_playstyles refuses outside Player Career", function()
    local ok, msg = H.turbo().run("pap_playstyles")
    H.eq(ok, false); H.has(msg, "not in Player Career")
end)

H.case("custom_headassets: empty map refused, map applied, unknown player reported", function()
    local ok, msg = H.turbo().run("custom_headassets")
    H.eq(ok, false); H.has(msg, "map is empty")
    H.write_config({ modules = { custom_headassets = { map = { ["1001"] = 158023, ["1003"] = 20801, ["777"] = 5 } } } })
    ok, msg = H.script("turbo_custom_headassets")
    ok, msg = H.turbo().run("custom_headassets")
    H.eq(ok, true, msg); H.has(msg, "updated 2 of 3"); H.has(msg, "not found: 777")
    local rec = sim:find_row("players", "playerid", 1001)
    H.eq(sim:value("players", rec, "headassetid"), 158023, "asset")
    H.eq(sim:value("players", rec, "hashighqualityhead"), 1, "hq")
    H.eq(sim:value("players", rec, "headclasscode"), 0, "class")
end)

H.case("custom_headassets refuses an out-of-range asset before writing anything", function()
    H.write_config({ modules = { custom_headassets = { map = { ["1005"] = 5, ["1007"] = 4000000 } } } })
    local ok, msg = H.turbo().run("custom_headassets")
    H.eq(ok, false); H.has(msg, "outside the field range")
    local rec = sim:find_row("players", "playerid", 1005)
    H.eq(sim:value("players", rec, "headassetid"), 0, "untouched")
end)

H.case("custom_tattoos applies the configured field", function()
    H.write_config({ modules = { custom_tattoos = { field = "tattooleftarm", map = { ["2001"] = 70, ["2002"] = 666 } } } })
    local ok, msg = H.turbo().run("custom_tattoos")
    H.eq(ok, true, msg)
    H.eq(sim:value("players", sim:find_row("players", "playerid", 2002), "tattooleftarm"), 666, "tattoo")
    H.write_config({ modules = { custom_tattoos = { field = "overallrating" } } })
    ok, msg = H.turbo().run("custom_tattoos")
    H.eq(ok, false); H.has(msg, "tattoo field")
end)

H.case("delete_generated_players lists without confirm, deletes with confirm", function()
    local ok, msg = H.turbo().run("delete_generated_players")
    H.eq(ok, true, msg); H.has(msg, "5 generated players found")
    H.eq(sim:count_calls("DeletePlayer"), 0, "nothing deleted")
    H.write_config({ modules = { delete_generated_players = { confirm = true } } })
    ok, msg = H.turbo().run("delete_generated_players")
    H.eq(ok, true, msg); H.has(msg, "deleted 5")
    H.eq(sim:find_row("players", "playerid", 460003), nil, "gone")
    H.ok(sim:find_row("players", "playerid", 1001) ~= nil, "others kept")
    ok, msg = H.turbo().run("delete_generated_players")
    H.has(msg, "no players with playerid >= 460000")
end)

H.case("extend_cpu_contracts adds years, caps at field max, skips your squad", function()
    local rec_cpu = sim:find_row("players", "playerid", 2010)
    sim:set_field(rec_cpu, sim.tables.players.contractvaliduntil, 2045)
    local ok, msg = H.turbo().run("extend_cpu_contracts")
    H.eq(ok, true, msg)
    H.eq(sim:value("players", sim:find_row("players", "playerid", 2001), "contractvaliduntil"), 2033, "+5")
    H.eq(sim:value("players", rec_cpu, "contractvaliduntil"), 2047, "capped")
    H.eq(sim:value("players", sim:find_row("players", "playerid", 1001), "contractvaliduntil"), 2028, "user untouched")
    H.has(msg, "26 of your players excluded")
end)

H.case("extend_user_contracts without career_playercontract updates players table only", function()
    H.write_config({ modules = { extend_user_contracts = { years = 4 } } })
    local ok, msg = H.turbo().run("extend_user_contracts")
    H.eq(ok, true, msg)
    H.eq(sim:value("players", sim:find_row("players", "playerid", 1010), "contractvaliduntil"), 2031, "2027+4")
    H.has(msg, "career_playercontract not present")
end)

H.case("needs_cm modules refuse outside career mode", function()
    sim.in_cm = false
    local ok, msg = H.turbo().run("extend_user_contracts")
    H.eq(ok, false); H.has(msg, "needs a loaded career save")
    sim.in_cm = true
end)

H.case("no unmapped memory reads", function()
    H.eq(sim.unmapped_reads, 0, "unmapped reads")
end)

-- Player Career world
sim = H.setup({ in_cm = true })
W.build(sim, { player_career = true, career_playercontract = true, playerloans = true })

H.case("pap_playstyles sets all traits for the PAP player", function()
    local ok, msg = H.turbo().run("pap_playstyles")
    H.eq(ok, true, msg)
    local rec = sim:find_row("players", "playerid", 1001)
    H.eq(sim:value("players", rec, "trait1"), (1 << 30) - 1, "trait1 max")
    H.eq(sim:value("players", rec, "icontrait1"), (1 << 30) - 1, "icontrait1")
    H.eq(sim:value("players", rec, "trait2"), 1535, "trait2")
    H.eq(sim:value("players", sim:find_row("players", "playerid", 1002), "trait1"), 0, "others untouched")
end)

H.case("pap_playstyles auto re-applies after the game resets traits", function()
    H.write_config({ auto = { pap_playstyles = { enabled = true } } })
    H.turbo().boot()
    local rec = sim:find_row("players", "playerid", 1001)
    sim:set_field(rec, sim.tables.players.trait1, 5)
    sim:fire("post__CareerModeEvent", 0, 29, 0)   -- POST_LOAD_PREPARE
    H.eq(sim:value("players", rec, "trait1"), (1 << 30) - 1, "re-applied")
end)

H.case("extend_user_contracts with career_playercontract skips loaned-in", function()
    local ok, msg = H.turbo().run("extend_user_contracts")
    H.eq(ok, true, msg)
    H.has(msg, "career_playercontract: 25 rows set to 48 months")
    H.has(msg, "1 loaned-in players skipped")
    local c = sim:find_row("career_playercontract", "playerid", 1002)
    H.eq(sim:value("career_playercontract", c, "duration_months"), 48, "months")
    H.eq(sim:value("career_playercontract", c, "contract_date"), 20270115, "date reset")
    local loan = sim:find_row("career_playercontract", "playerid", W.LOANED_IN)
    H.eq(sim:value("career_playercontract", loan, "duration_months"), 24, "loan untouched")
end)

H.case("no unmapped memory reads (player career world)", function()
    H.eq(sim.unmapped_reads, 0, "unmapped reads")
end)

H.finish()
