package.path = (debug.getinfo(1, "S").source:sub(2):match("(.*/)") or "./") .. "?.lua;" .. package.path
local H = require 'h'
local W = require 'world'

print("t03 exports, head models, bans, jersey numbers")

local sim = H.setup({ in_cm = true })
W.build(sim, {})

H.case("export_season_stats writes quoted CSV, skips zero-appearance lines", function()
    local ok, msg = H.turbo().run("export_season_stats")
    H.eq(ok, true, msg)
    local files = H.ls_out("^turbo_season_stats_2027_01_15%.csv$")
    H.eq(#files, 1, "file")
    local lines = H.csv_lines(H.out(files[1]))
    H.eq(#lines, 3, "header + 2 rows")
    H.has(lines[1], "position,playerid,playername,team,competition,appearances,AVG")
    H.has(lines[2], ",1010,Player 1010,Arsenal,Comp 100,20,7.25,3,12,5,1,0,0,0,0,0", "top scorer row")
    H.has(lines[3], '"Inter, Milano"', "comma quoted")
end)

H.case("export_season_stats only_user_team", function()
    H.write_config({ modules = { export_season_stats = { only_user_team = true } } })
    local ok, msg = H.turbo().run("export_season_stats")
    H.eq(ok, true, msg); H.has(msg, "1 stat lines")
end)

H.case("export_fixtures with the FC 26 layout", function()
    local ok, msg = H.turbo().run("export_fixtures")
    H.eq(ok, true, msg); H.has(msg, "4 fixtures"); H.has(msg, "+0x60 / +0x88")
    local lines = H.csv_lines(H.out("turbo_fixtures_2027_01_15.csv"))
    H.eq(#lines, 5, "header + 4")
    H.eq(lines[2], 'Comp 100,100,20260815,1500,1,Arsenal,2,1,"Inter, Milano",241,1', "first fixture, quoted team name")
    H.has(lines[5], ",,", "future fixture has empty scores")
end)

H.case("export_transfer_history with the FC 26 layout", function()
    local ok, msg = H.turbo().run("export_transfer_history")
    H.eq(ok, true, msg); H.has(msg, "3 moves"); H.has(msg, "+0x1DD0")
    local lines = H.csv_lines(H.out("turbo_transfer_history_2027_01_15.csv"))
    H.eq(lines[1], "type,date,playerid,playername,teamfromid,teamfromname,teamtoid,teamtoname,fee,exchangeplayerid,exchangeplayername,total_deal_value")
    H.eq(lines[2], "transfer,20260801,2001,Player 2001,2,Team 2,3,Team 3,12500000,,,12500000", "ai transfer with fee")
    H.eq(lines[3], "loan,20260815,2005,Player 2005,3,Team 3,4,Team 4,0,,,0", "ai loan")
    H.eq(lines[4], "transfer,20260820,2009,Player 2009,4,Team 4,1,Arsenal,3000000,,,3000000", "user purchase")
end)

H.case("calibration cache written", function()
    local d = H.read(H.out("turbo_calibration.json"))
    H.ok(d and d:find("fixtures_off") and d:find("storage_off"), "calibration json: " .. tostring(d))
end)

H.case("headmodels capture then apply", function()
    local ok, msg = H.script("turbo_headmodels_capture")
    ok, msg = H.turbo().run("headmodels", { mode = "capture" })
    H.eq(ok, true, msg)
    local list = H.read(H.out("headmodels_fc27.json"))
    H.ok(list and list:sub(1, 1) == "[", "json list")
    local n = select(2, list:gsub(",", ",")) + 1
    H.ok(n >= 40, "captured " .. n)
    ok, msg = H.turbo().run("headmodels", { mode = "apply", min_list_size = 10 })
    H.eq(ok, true, msg)
    local odd = sim:find_row("players", "playerid", 2001)
    H.eq(sim:value("players", odd, "headclasscode"), 1, "generic for players without own head")
    local even = sim:find_row("players", "playerid", 2002)
    H.eq(sim:value("players", even, "headassetid"), 2002, "real head")
end)

H.case("headmodels apply refuses a too-small list", function()
    local ok, msg = H.turbo().run("headmodels", { mode = "apply" })
    H.eq(ok, false); H.has(msg, "fewer than min_list_size 100")
end)

H.case("headmodels refuses path tricks in list_file", function()
    local ok, msg = H.turbo().run("headmodels", { mode = "capture", list_file = "..\\x.json" })
    H.eq(ok, false); H.has(msg, "plain file name")
end)

H.case("transfer bans: ban all, list (types labelled), unban all", function()
    sim.bans = { { id = 2001, member_type = 1, date_end = 20271231 } }
    local ok, msg = H.turbo().run("transfer_bans", { mode = "ban_all_teams" })
    H.eq(ok, true, msg); H.has(msg, "16 teams transfer-banned until 20990101")
    H.eq(sim:count_calls("cSaveTransferBans"), 1, "saved")
    ok, msg = H.turbo().run("transfer_bans", { mode = "list" })
    H.eq(ok, true, msg); H.has(msg, "17 active transfer bans")
    local lines = H.csv_lines(H.out("turbo_transfer_bans.csv"))
    H.eq(lines[2], "player,2001,Player 2001,20271231", "player ban labelled player")
    ok, msg = H.turbo().run("transfer_bans", { mode = "unban_all_teams" })
    H.eq(ok, true, msg); H.has(msg, "16 team bans removed")
    H.eq(#sim.bans, 1, "player ban kept")
    ok, msg = H.turbo().run("transfer_bans", { mode = "ban_all_teams", exclude_user_team = true })
    H.has(msg, "15 teams"); H.has(msg, "your club excluded")
    ok, msg = H.turbo().run("transfer_bans", { mode = "ban_all_teams", ban_until = 20991399 })
    H.eq(ok, false); H.has(msg, "YYYYMMDD")
end)

H.case("team_jersey_numbers defaults to your club", function()
    local ok, msg = H.turbo().run("team_jersey_numbers")
    H.eq(ok, true, msg); H.has(msg, "Arsenal (ID 1): 26 players")
    local lines = H.csv_lines(H.out("turbo_jersey_numbers_1.csv"))
    H.eq(lines[2], "1,1001,Player 1001", "sorted by number")
end)

H.case("export_table writes rows and field ranges", function()
    local ok, msg = H.turbo().run("export_table", { tables = { "teams", "formations" } })
    H.eq(ok, true, msg); H.has(msg, "teams: 16 rows, 3 fields"); H.has(msg, "formations: 2 rows, 3 fields")
    local f = H.csv_lines(H.out("turbo_table_teams_fields.csv"))
    H.eq(f[2], "teamid,int,0,262143,", "teamid range")
    H.eq(f[3], "teamname,string,,,30", "teamname length")
    local fm = H.csv_lines(H.out("turbo_table_formations.csv"))
    H.eq(fm[2], "3,0.2500,1", "float formatting")
    ok, msg = H.turbo().run("export_table", { tables = { "nope" } })
    H.eq(ok, false); H.has(msg, "table not found: nope")
end)

H.case("no unmapped memory reads", function()
    H.eq(sim.unmapped_reads, 0, "unmapped reads")
end)

-- Shifted layouts (what FC 27 may have done): Turbo must find them
sim = H.setup({ in_cm = true })
W.build(sim, { fixtures_off = 0x70, standings_off = 0x98, storage_off = 0x1E40 })

H.case("export_fixtures finds moved lists", function()
    local ok, msg = H.turbo().run("export_fixtures")
    H.eq(ok, true, msg); H.has(msg, "+0x70 / +0x98")
end)

H.case("export_transfer_history finds moved storage", function()
    local ok, msg = H.turbo().run("export_transfer_history")
    H.eq(ok, true, msg); H.has(msg, "3 moves"); H.has(msg, "+0x1E40")
end)

H.case("second run uses the cached calibration", function()
    local d = H.read(H.out("turbo_calibration.json"))
    H.ok(d:find('"storage_off":7744') ~= nil, "cached 0x1E40: " .. tostring(d))
    local ok, msg = H.turbo().run("export_transfer_history")
    H.eq(ok, true, msg)
end)

H.case("no unmapped memory reads (shifted)", function()
    H.eq(sim.unmapped_reads, 0, "unmapped reads")
end)

-- Broken layouts: Turbo must refuse and write nothing
sim = H.setup({ in_cm = true })
W.build(sim, { fixtures_off = false, storage_off = false })

H.case("export_fixtures refuses unrecognised memory", function()
    local ok, msg = H.turbo().run("export_fixtures")
    H.eq(ok, false); H.has(msg, "no fixtures/standings lists")
    H.eq(#H.ls_out("^turbo_fixtures"), 0, "no file")
end)

H.case("export_transfer_history refuses unrecognised memory", function()
    local ok, msg = H.turbo().run("export_transfer_history")
    H.eq(ok, false); H.has(msg, "no negotiations storage")
    H.eq(#H.ls_out("^turbo_transfer_history"), 0, "no file")
end)

H.case("unmapped reads during broken-layout search are reported", function()
    print("    (info) unmapped reads in broken-layout search: " .. sim.unmapped_reads)
    H.eq(sim.unmapped_reads, 0, "unmapped reads")
end)

H.finish()
